### ISSUE TITLE
Tags for instrument types

### ISSUE THREAD

**Issue by austozi** [SheetAble/SheetAble#13]
**Is your feature request related to a problem? Please describe.**
I have sheets for different musical instruments in my collection. It would be good to be able to organise them according to the instrument type. Some sheets are written for multiple instruments, so it would be good to be able to specify multiple instrument types for each sheet.

**Describe the solution you'd like**
Create a metadata field for instrument type, and allow multiple user-defined values. Probably best implemented using tags. 

**Describe alternatives you've considered**
Folders for instruments, probably, but they are less versatile and cannot accommodate multiple instruments per sheet without file duplication.

**Comment by vallezw** [comment]
Hey, good enhancement idea! I'll try to add it after I finished working on the Search Bar so I'm estimating it to be implemented around release v0.6, v0.7.

**Comment by gorgobacka** [comment]
I really like this idea, because the instrument is very fundamental for sheet music. However, I wouldn't cluster them with regular tags, because tags can be anything (eg genre, any subjective vales). I would suggest to distinguish the values for instruments somehow from other information.

If you still want to use tags here that can included other info as well, you could use the approach that Musicbrainz is using for their genres. They have a predefined list of genre tags and if a tag belongs to that list, they display it separated from regular tags in the UI.

**Comment by vallezw** [comment]
> I really like this idea, because the instrument is very fundamental for sheet music. However, I wouldn't cluster them with regular tags, because tags can be anything (eg genre, any subjective values). Therefore, I would suggest to distinguish the values for instruments somehow from other information.
> 
> If you still want to use tags here that can included other info as well, you could use the approach that Musicbrainz is using for their genres. They have a predefined list of genre tags and if a tag belongs to that list, they display it separated from regular tags in the UI.

So you mean that there should be one list of tags and one list of genre tags. In the normal tag list there is any kind of value from the user **including instruments** and in the other list of genres, you can just select a genre from a specific genre list. 

Perhaps we should rather make a separate list of instruments than genres since genres would also work with normal tags I think. What do you think about this?

**Comment by vallezw** [comment]
Alright, I understand what you mean by that. However I am currently working on implementing tags since that would be a general solution for everything in the first place, but I will implement more specific values for genres and instruments later on
