### ISSUE TITLE
Bug: Composer and Sheets with special characters

### ISSUE THREAD

**Issue by gorgobacka** [SheetAble/SheetAble#4]
**Describe the bug**
The composer and the uploaded sheet is not usable, if any special characters (e.g. &) is used in the name of composer.

**To Reproduce**
1. Upload a sheet and set the composer name for example to: "Irving Kahal & Sammy Fain"
or
2. Use a working composer and edit it's name. Include e.g. a "%" somewhere.

**Expected behavior**
Such a character shouldn't have any effect and everything should work as normal.

**Version**
I used v0.2.

**Comment by vallezw** [comment]
Hey, thanks for the issue. I will look into fixing that issue in release 0.3/0.4. Please be patient until then.

**Comment by sylvan-c** [comment]
This issue also affects the sheet music name; asterisks (') and sharp signs (#) cause the sheets to be unreadable and undeletable. Clicking on the broken preview takes you to a blank whitescreen, and pressing the back button on firefox leads to another whitescreen which is fixed by refreshing the page.

https://user-images.githubusercontent.com/67205854/133598418-e0f92145-a955-4f63-83c8-6715cb7d1493.mp4

**Comment by vallezw** [comment]
Ah yes, I already planned on fixing that too, but thanks for the update! I am planning on refactoring the whole backend naming process so these issues won't be a problem anymore. Like I already mentioned in my early comment, this issue is probably fixed in the next 2 patches, since I think it is a major issue for the experience.

**Comment by vallezw** [comment]
Alright, that bug is fixed now and will be released in v0.3. Thanks for the issue!
